spring.application.name=maison
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update

# Aumentar el tamaño máximo de las peticiones HTTP y carga de archivos
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Aumentar la capacidad de procesamiento de la cabecera y cuerpo de Tomcat
server.tomcat.max-http-form-post-size=50MB
server.tomcat.max-swallow-size=50MB

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
